language: c

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl
    - uscan --force-download
    - sudo apt-get purge -qq libwww-perl
    - sudo apt-get autoremove -qq
    - sudo apt-get install -qq --no-install-recommends debhelper dpatch

script:
    - debuild -uc -us

#notifications:
#  email: false
